package eli.auca.model;
// Generated May 15, 2020 12:56:01 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String username;
     private String name;
     private String password;
     private String secQ;
     private String answer;

    public Account() {
    }

    public Account(String username, String name, String password, String secQ, String answer) {
       this.username = username;
       this.name = name;
       this.password = password;
       this.secQ = secQ;
       this.answer = answer;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecQ() {
        return this.secQ;
    }
    
    public void setSecQ(String secQ) {
        this.secQ = secQ;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


