package eli.auca.model;
// Generated May 15, 2020 12:56:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Checkinout generated by hbm2java
 */
public class Checkinout  implements java.io.Serializable {


     private Integer SN;
     private Date dateTime;
     private String status;
     private String operationCategory;

    public Checkinout() {
    }

    public Checkinout(Date dateTime, String status, String operationCategory) {
       this.dateTime = dateTime;
       this.status = status;
       this.operationCategory = operationCategory;
    }
   
    public Integer getSN() {
        return this.SN;
    }
    
    public void setSN(Integer SN) {
        this.SN = SN;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getOperationCategory() {
        return this.operationCategory;
    }
    
    public void setOperationCategory(String operationCategory) {
        this.operationCategory = operationCategory;
    }




}


